import "../style/global.css";
import { Noto_Sans_TC } from "next/font/google";

export const metadata = {
  title: "Omar You",
  description: "Generated by create next app",
};
const roboto = Noto_Sans_TC({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
